# Generated by Django 2.2.5 on 2019-12-03 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='img_perfil',
            field=models.ImageField(default='images/no-image.png', upload_to='images/'),
        ),
    ]
