# Generated by Django 2.2.5 on 2019-10-04 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_myuser_activo'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='descripcion',
            field=models.TextField(max_length=1000, null=True),
        ),
    ]
