# Generated by Django 2.2.5 on 2019-10-04 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_myuser_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='descripcion',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
