# Generated by Django 2.2.5 on 2019-10-07 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_auto_20191004_1318'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='img_perfil',
            field=models.ImageField(default='no-image.png', upload_to='images/'),
        ),
    ]
