# Generated by Django 2.2.6 on 2019-11-03 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0010_auto_20191101_1613'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myuser',
            old_name='activo',
            new_name='is_active',
        ),
        migrations.AlterField(
            model_name='myuser',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
