# Generated by Django 2.2.5 on 2019-12-03 02:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('primer_nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('nacimiento', models.DateField()),
                ('muerte', models.DateField(blank=True, null=True, verbose_name='Fallecimiento')),
                ('descripcion', models.TextField(blank=True, help_text='bibliografía corta del autor', max_length=2000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Editorial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(help_text='Ingrese el nombre del género (p. ej. Ciencia Ficción, Poesía Francesa etc.)', max_length=200)),
                ('activo', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Titulo')),
                ('portada', models.ImageField(default='images/no-book-image.jpg', null=True, upload_to='images/')),
                ('resumen', models.TextField(help_text='Ingrese el resumen del libro', max_length=2000)),
                ('isbn', models.CharField(help_text='13 Caracteres <a href="https://www.isbn-international.org/content/what-isbn">ISBN number</a>', max_length=13, verbose_name='ISBN')),
                ('fech_salida', models.DateField(blank=True, null=True, verbose_name='Fecha de publicación')),
                ('activo', models.BooleanField(default=True)),
                ('copias', models.IntegerField(blank=True, default=1)),
                ('estrellas', models.FloatField(default=0)),
                ('paginas', models.IntegerField(blank=True, null=True)),
                ('autor', models.ManyToManyField(help_text='selecciones un autor', to='Biblioteca.Autor')),
                ('editorial', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Biblioteca.Editorial')),
                ('genero', models.ManyToManyField(help_text='Seleccione un genero', to='Biblioteca.Genero')),
            ],
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slider1', models.ImageField(default='images/no-book-image.jpg', upload_to='images/')),
                ('slider2', models.ImageField(default='images/no-book-image.jpg', upload_to='images/')),
                ('slider3', models.ImageField(default='images/no-book-image.jpg', upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Puntuacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.FloatField(blank=True, null=True)),
                ('fecha', models.DateTimeField(auto_now=True, null=True)),
                ('libro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Biblioteca.Libro')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InstanciaLibro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fech_inicio', models.DateField(verbose_name='Fecha de entrega')),
                ('fech_vencimiento', models.DateField(verbose_name='Fecha de devolución')),
                ('libro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Biblioteca.Libro')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
