# Generated by Django 2.2.6 on 2019-10-08 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Biblioteca', '0003_instancialibro'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='portada',
            field=models.ImageField(default='images/no-book-image.jpg', upload_to='images/'),
        ),
    ]
