# Generated by Django 2.2.5 on 2019-10-10 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Biblioteca', '0004_libro_portada'),
    ]

    operations = [
        migrations.AddField(
            model_name='genero',
            name='activo',
            field=models.BooleanField(default=False),
        ),
    ]
