# Generated by Django 2.2.5 on 2019-10-12 21:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Biblioteca', '0005_genero_activo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Editorial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80, unique=True)),
            ],
        ),
        migrations.RenameField(
            model_name='libro',
            old_name='puntuacion',
            new_name='estrellas',
        ),
        migrations.AddField(
            model_name='autor',
            name='descripcion',
            field=models.TextField(blank=True, help_text='bibliografía corta del autor', max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='instancialibro',
            name='libro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Biblioteca.Libro'),
        ),
        migrations.AlterField(
            model_name='instancialibro',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='libro',
            name='autor',
            field=models.ManyToManyField(help_text='selecciones un autor', to='Biblioteca.Autor'),
        ),
        migrations.AlterField(
            model_name='libro',
            name='genero',
            field=models.ManyToManyField(help_text='Seleccione un genero', to='Biblioteca.Genero'),
        ),
        migrations.CreateModel(
            name='Puntuacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.FloatField(blank=True, null=True)),
                ('fecha', models.DateTimeField(auto_now=True, null=True)),
                ('libro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Biblioteca.Libro')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='libro',
            name='editorial',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Biblioteca.Editorial'),
        ),
    ]
