# Generated by Django 2.2.5 on 2019-10-13 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Biblioteca', '0006_auto_20191012_1829'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='paginas',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
