# Generated by Django 2.2.5 on 2019-10-29 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Biblioteca', '0007_libro_paginas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autor',
            name='nacimiento',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='genero',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='libro',
            name='estrellas',
            field=models.FloatField(default=0),
        ),
    ]
