# Generated by Django 2.2.6 on 2019-11-01 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Biblioteca', '0008_auto_20191029_1934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='portada',
            field=models.ImageField(default='images/no-book-image.jpg', null=True, upload_to='images/'),
        ),
    ]
