# Generated by Django 2.2.6 on 2019-11-03 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Biblioteca', '0009_auto_20191101_1613'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slider1', models.ImageField(upload_to='images/')),
                ('slider2', models.ImageField(upload_to='images/')),
                ('slider3', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
