# Generated by Django 2.2.5 on 2019-11-12 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Biblioteca', '0009_auto_20191103_2037'),
        ('Biblioteca', '0010_slider'),
    ]

    operations = [
    ]
