# Generated by Django 2.2.6 on 2019-11-16 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Biblioteca', '0010_slider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='slider1',
            field=models.ImageField(default='images/no-book-image.jpg', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='slider2',
            field=models.ImageField(default='images/no-book-image.jpg', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='slider3',
            field=models.ImageField(default='images/no-book-image.jpg', upload_to='images/'),
        ),
    ]
