# Generated by Django 2.2.3 on 2019-11-18 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Biblioteca', '0011_auto_20191115_2331'),
        ('Biblioteca', '0011_merge_20191112_1725'),
    ]

    operations = [
    ]
